name: Build
on:
  push:

jobs:
# Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: sudo apt-get -y install autoconf automake autopoint gettext build-essential git libfuse-dev libtool pkg-config
      - run: sudo apt-get install build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev libffi6
      - run: sudo apt-get install -y libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good
      - run: sudo apt-get install libffi-dev
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        id: buildozer
        with:
         workdir: .
         buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
