name: Build
on:
  push:

jobs:
# Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        run: sudo apt-get -y install autoconf automake autopoint build-essential git libfuse-dev libtool pkg-config
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        id: buildozer
        with:
         workdir: .
         buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
